# Generated by Django 4.2.5 on 2023-09-21 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_origin', '0002_alter_tokenjwt_t_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenjwt',
            name='t_limit',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 13, 10, 19, 190299, tzinfo=datetime.timezone.utc)),
        ),
    ]
