# Generated by Django 4.2.5 on 2023-10-06 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_origin', '0028_alter_tokenjwt_t_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenjwt',
            name='t_limit',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 7, 12, 40, 967771, tzinfo=datetime.timezone.utc)),
        ),
    ]
