# Generated by Django 4.2.5 on 2023-09-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_path', models.FileField(upload_to='files/')),
                ('f_date', models.DateTimeField(auto_now_add=True)),
                ('u_id', models.CharField(max_length=150, unique=True)),
                ('f_name', models.CharField(max_length=255)),
                ('f_type', models.CharField(max_length=10)),
            ],
        ),
    ]
