# Generated by Django 4.2.5 on 2023-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_file', '0003_alter_uploadedfile_f_path_alter_uploadedfile_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='f_deleted',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='f_size',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
