# Generated by Django 4.2.5 on 2023-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_file', '0004_remove_uploadedfile_f_deleted_uploadedfile_f_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='f_deleted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
