# Generated by Django 4.2.5 on 2023-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_file', '0006_uploadedfile_f_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='f_md5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
