# Generated by Django 4.2.5 on 2023-10-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_file', '0007_uploadedfile_f_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='s_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='s_id',
            field=models.IntegerField(default=0),
        ),
    ]
