# Generated by Django 4.2.5 on 2023-10-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_file', '0008_uploadedfile_s_done_uploadedfile_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='u_id',
            field=models.CharField(max_length=255),
        ),
    ]
