# Generated by Django 4.2.5 on 2023-09-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='f_deleted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
