# Generated by Django 4.2.5 on 2023-11-21 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_origin', '0038_alter_tokenjwt_t_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenjwt',
            name='t_limit',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 22, 34, 48, 541497, tzinfo=datetime.timezone.utc)),
        ),
    ]
