# Generated by Django 4.2.5 on 2023-11-09 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_origin', '0037_alter_tokenjwt_t_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenjwt',
            name='t_limit',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 21, 1, 58, 94371, tzinfo=datetime.timezone.utc)),
        ),
    ]
