# Generated by Django 4.2.5 on 2023-10-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzereport',
            name='f_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='analyzereport',
            name='r_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='analyzereport',
            name='u_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='analyzereport',
            name='u_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
