# Generated by Django 4.2.5 on 2023-10-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_analyzereport_f_path_alter_analyzereport_r_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzereport',
            name='u_name',
        ),
    ]
