# Generated by Django 4.2.5 on 2023-11-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_analyzequeue_alter_analyzereport_f_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzequeue',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.analyzereport'),
        ),
    ]
