# Generated by Django 4.2.5 on 2023-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_alter_analyzereport_f_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzequeue',
            name='q_try',
            field=models.IntegerField(default=0),
        ),
    ]
