# Generated by Django 4.2.5 on 2023-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_alter_analyzequeue_r_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzereport',
            name='f_path',
            field=models.FileField(upload_to='B:\\est-project\\new_ver_JungSup\\files\\apk'),
        ),
    ]
