# Generated by Django 4.2.5 on 2023-11-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
