# Generated by Django 4.2.5 on 2023-11-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzequeue',
            name='o_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
