# Generated by Django 4.2.5 on 2023-09-25 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_origin', '0004_alter_tokenjwt_t_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenjwt',
            name='t_limit',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 7, 59, 20, 81179, tzinfo=datetime.timezone.utc)),
        ),
    ]
