# Generated by Django 4.2.5 on 2023-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_apk_user', models.CharField(default='', max_length=255)),
                ('s_apk_path', models.CharField(default='', max_length=255)),
                ('s_apk_date', models.DateTimeField(auto_now_add=True)),
                ('a_apk_name', models.CharField(max_length=255)),
                ('a_apk_crc32', models.JSONField(default=dict)),
                ('a_apk_file_list', models.JSONField(default=dict)),
                ('a_apk_package_name', models.CharField(default='', max_length=255)),
                ('a_apk_min_sdk_ver', models.CharField(default='', max_length=255)),
                ('a_apk_max_sdk_ver', models.CharField(default='', max_length=255, null=True)),
                ('a_apk_target_sdk_ver', models.CharField(default='', max_length=255)),
                ('a_apk_android_ver_code', models.CharField(default='', max_length=255)),
                ('a_apk_signed_v1', models.BooleanField(default=False)),
                ('a_apk_signed_v2', models.BooleanField(default=False)),
                ('a_apk_signed_v3', models.BooleanField(default=False)),
                ('a_apk_main_activity', models.CharField(default='', max_length=255)),
                ('a_apk_activities', models.JSONField(default=dict)),
                ('a_apk_get_permissions', models.JSONField(default=dict)),
                ('a_apk_get_declared_permissions', models.JSONField(default=dict)),
                ('a_apk_services', models.JSONField(default=dict)),
                ('a_apk_receivers', models.JSONField(default=dict)),
                ('a_apk_intent_filters', models.JSONField(default=dict)),
                ('a_apk_providers', models.JSONField(default=dict)),
                ('a_apk_libraries', models.JSONField(default=dict)),
                ('a_apk_icon_path', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
