# Generated by Django 4.2.5 on 2023-10-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='s_apk_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='s_apk_fid',
            field=models.IntegerField(default=0),
        ),
    ]
