# Generated by Django 4.2.5 on 2023-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='a_apk_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
